name: 'Check'

on:
  push:
    branches:
      - 'master'

  pull_request:
    types:
      - opened
      - synchronize

  workflow_dispatch:

jobs:
  lint:
    uses: SlashNephy/.github/.github/workflows/yarn-lint.yml@master
    with:
      pre-script: 'build'
      script: 'lint'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request'
    uses: SlashNephy/.github/.github/workflows/yarn-format.yml@master
    with:
      pre-script: 'build'
      script: 'format'
    permissions:
      contents: 'write'

  publish:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    needs: lint
    uses: SlashNephy/.github/.github/workflows/yarn-publish.yml@master
    with:
      pre-script: 'bump-version'
      script: 'publish'
      commit-message: '🔨 Bump version'
    permissions:
      contents: 'write'
    secrets:
      NODE_AUTH_TOKEN: '${{ secrets.NPM_ACCESS_TOKEN }}'
